Dev->main
Cartmanezs/FruitsAndBerries pull request #1
Opened 2024-01-04 17:21 UTC by Cartmanezs

2024-01-06 20:07 UTC, valself reviewed
I'm waiting for the changes

2024-01-06 20:07 UTC, valself commented on FruitsAndBerries/Main/FruitsAndBerriesInteractor.swift
> +                let dispatchGroup = DispatchGroup()
Looks too complex!
Why do you use dispatchgroups here? You call method that already has a completion. Unwrap this completion and handle it. That's all. 

Read about KISS principle.

2024-01-06 20:07 UTC, valself commented on FruitsAndBerries/Main/FruitsAndBerriesInteractor.swift
> +                    self.fruitsBerriesRepository.fetchImage(imageUrlString) { resultImage in
memory leak!

2024-01-06 20:07 UTC, valself commented on FruitsAndBerries/Main/FruitsAndBerriesInteractor.swift
> +                self.presenter?.presentDetails(response: loadDetailsResponse)
leak

2024-01-06 20:07 UTC, valself commented on FruitsAndBerries/Main/FruitsAndBerriesInteractor.swift
> +                print("Error fetching details: \(error)")
how user will be notified about this case?

2024-01-06 20:07 UTC, valself commented on FruitsAndBerries/Main/FruitsAndBerriesInteractor.swift
> +                let responseItems = itemsResponse.items.compactMap { item in
Looks too complex again... Find more simple solution

2024-01-06 20:13 UTC, valself commented on FruitsAndBerries/Detail/FruitsAndBerriesDetailsViewController.swift
> +final class FruitsAndBerriesDetailsViewController: UIViewController {
Ok I see this text in the requirements

`Although 2 screens need to be implemented, they should both be a part of the same module. Navigating between them should happen completely in the View layer (not through the router) by simply pushing the details screen (View Controller to be created) into the navigation controller.`

2024-01-06 20:16 UTC, Cartmanezs commented on FruitsAndBerries/API/Endpoints.swift
> +    static func image(imageUrl: String) -> Self {
Changed to imageUrlString

2024-01-06 20:17 UTC, Cartmanezs commented on FruitsAndBerries/API/DError.swift
> +enum DError: Error {
Changed to FBError -  FruitsAndBerrieError

2024-01-08 15:53 UTC, valself commented on FruitsAndBerries/API/DError.swift
> +enum DError: Error {
You didn't change this name in the header

2024-01-08 15:54 UTC, valself commented on FruitsAndBerries/API/Endpoints.swift
> +    static func image(imageUrl: String) -> Self {
> Changed to imageUrlString

I don't see it

2024-01-08 15:56 UTC, Cartmanezs commented on FruitsAndBerries/API/Endpoints.swift
> +    static func image(imageUrl: String) -> Self {
for now it's imageUrl: URL

2024-01-08 16:46 UTC, Cartmanezs commented on FruitsAndBerries/Repositories/FruitsAndBerrieRepository.swift
> +            preconditionFailure("Unable to construct a valid URL for given endpoint: \(endpoint)")
I've already checked. It doesn't crash.

2024-01-09 11:37 UTC, valself requested changes

2024-01-09 12:33 UTC, closed without merging